services:
  - type: web
    name: ocr-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: uvicorn ocr_api:app --host 0.0.0.0 --port $PORT
